name: flutter_messaging_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  firebase_auth: ^0.16.0
  provider: ^4.1.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  get_it: ^4.0.2
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0  
  cloud_firestore: ^0.13.5
  image_picker: ^0.6.6+4
  firebase_storage: ^3.1.5
  intl: ^0.16.1  
  timeago: ^2.0.26
  firebase_messaging: ^6.0.15
  flutter_local_notifications: ^1.4.3
  http: ^0.12.1
  country_pickers: ^1.2.1
  progress_dialog: ^1.2.3
  fluttertoast: ^4.0.1
  shared_preferences: ^0.5.7+3
  firebase_core: ^0.4.4+3
  uuid: ^2.0.4
  google_maps_flutter: ^0.5.28+1
  datetime_picker_formfield: ^1.0.0
  google_maps_webservice: ^0.0.16
  flutter_google_places: ^0.2.5
  location: ^3.0.2
  flutter_calendar: ^0.0.9
  flutter_slidable: ^0.5.4  
  gson: ^0.1.4
  firebase_database: ^3.1.5
  badges: ^1.1.1
  video_player: ^0.10.11+1
  carousel_slider: ^2.1.0
  flutter_custom_clippers: ^1.1.1  
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # - images/
   - assets/logo.png
   - assets/sherry.jpg
   - assets/person.jpg
   - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
    - family: UbuntuLight
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
    - family: DosisMedium
      fonts:
        - asset: assets/fonts/dosis/Dosis-Medium.ttf
 